fix: validate_vars returns nothing, but must return convert_vars result
chaostoolkit/chaostoolkit pull request #213
Opened 2021-04-05 21:26 UTC by GLaN1K

From function docstring:

```
    """
    Process all `--var key=value` and return a dictionnary of them with the
    value converted to the appropriate type.
    """
```

But actually there was no return, therefore whole `--var` and `--var-file` thingy was not working

2021-04-06 09:09 UTC, Lawouach requested changes
Gah... How was this missed?! :)

LGTM, thanks.

However can I ask:

* At least one test showing the issue (and therefore fixed now)
* a changelog entry

Cheers

2021-04-06 16:36 UTC, GLaN1K commented
> How was this missed?! :)

Wondering too х) 

Here is my test:

```
   "configuration":{
      "aws_region":"us-west-2",
      "target_node":"will_be_filled_from_the_args",
   },
   "method":[
      {
         "name":"probe-ec2-instance",
         "type":"probe",
         "provider":{
            "type":"python",
            "module":"chaosaws.ec2.probes",
            "func":"count_instances",
            "arguments":{
               "filters":[
                  {
                     "Name":"tag:Name",
                     "Values":[
                        "${target_node}"
                     ]
                  }
               ]
            }
         }
```

As you can see, i defined variable `target_node ` and use it inside of args for `count_instances` func

Without fix:

```
glanik@Luna ~/b/c/ansible:chaostoolkit-poc 1> chaos --verbose run chaostoolkit/node-kill-es.json --var target_node=chostoolkit-01  2>&1 | grep "succeeded"

[2021-04-06 19:33:40 DEBUG] [activity:180]   => succeeded with '0'

With fix:

```
glanik@Luna ~/b/c/ansible:chaostoolkit-poc 1> chaos --verbose run chaostoolkit/node-kill-es.json --var target_node=chostoolkit-01  2>&1 | grep "succeeded"

[2021-04-06 19:34:36 DEBUG] [activity:180]   => succeeded with '1'
```

2021-04-06 16:42 UTC, GLaN1K commented
Changelog entry added!

2021-04-07 07:51 UTC, Lawouach commented
Ha, I much appreciate your swiftness. I should have clarified a simple unit test of the `validate_vars` would do :)

Once that's done, I'll merge this PR.

2021-05-31 06:03 UTC, Lawouach approved these changes

2021-05-31 06:03 UTC, Lawouach approved these changes

2021-05-31 06:04 UTC, merged