Adding pull request template
chaostoolkit/chaostoolkit pull request #218
Opened 2021-04-27 12:16 UTC by carrtim93

Added a pull request template to assist with onboarding contributors more efficiently.
Let me know if there is something that can be added to the template.

2021-04-30 13:41 UTC, Lawouach requested changes
Thanks. A few tweaks.

2021-04-30 13:41 UTC, Lawouach commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- issue goes here
A sentence would be better, something that says:

```
Please create an issue, to discuss the problem, and link it to this PR.
```

2021-04-30 13:41 UTC, Lawouach commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +# Screenshots
Not required. This is a command line tool, screenshots aren't usually very helpful.

2021-04-30 13:41 UTC, Lawouach commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +# Checklist
Please add a description before the list:

```
Please ensure that you have completed the following lists before submitting your PR:
```

2021-04-30 13:41 UTC, Lawouach commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] Squash Commits
```
Squashed commits to simplify and speed up the review
```

2021-09-13 15:54 UTC, CharlieMoon37 commented
I have created an updated template as per the changes requested here #237

2021-09-13 15:54 UTC, closed without merging